name: deploy-auth
on:
  push:
    branches:
      - master
    paths:
      - "auth/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t kaysongdocker/picspie-micro-auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: $${{ secrets.DOCKER_PASSWORD }}
          DOCKER_PASSWORD: $${{ secrets.DOCKER_PASSWORD }}
      - run: docker push kaysongdocker/picspie-micro-auth
      - uses: digitalocean push kaysongdocker/picspie-micro-auth
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save picspie
      - run: kubectl rollout restart deployment auth-depl
